/**
 * Alarm Events Test Data
 * For testing alarm_events API
 */

import type { AlarmEvent, GetAlarmEventsResult } from '@/api/alarm/model/alarmModel'
import dayjs from 'dayjs'

// Mock alarm events data
export const mockAlarmEvents: AlarmEvent[] = [
  {
    event_id: 'event-001',
    event_type: 'Fall',
    category: 'safety',
    alarm_level: '0',
    alarm_status: 'active',
    triggered_at: dayjs().subtract(1, 'hour').unix(),
    card_id: 'card-001',
    device_id: '9D8A32A1CD2B',
    device_name: '201Radar',
    resident_id: 'resident-001',
    resident_name: 'John Doe',
    resident_network: 'network',
    resident_gender: 'Female',
    resident_age: 47,
    location_tag: 'Building A',
    building: 'A',
    floor: '2F',
    unit_name: '201-A',
    address_display: 'Building A-A-E203',
  },
  {
    event_id: 'event-002',
    event_type: 'Radar_AbnormalHeartRate',
    category: 'clinical',
    alarm_level: '1',
    alarm_status: 'active',
    triggered_at: dayjs().subtract(2, 'hours').unix(),
    card_id: 'card-002',
    device_id: 'device-002',
    device_name: 'Radar02',
    resident_id: 'resident-002',
    resident_name: 'Jane Smith',
    resident_network: 'network',
    resident_gender: 'Male',
    resident_age: 65,
    location_tag: 'Building A',
    building: 'A',
    floor: '2F',
    unit_name: 'E204',
    address_display: 'Building A-A-E204',
  },
  {
    event_id: 'event-003',
    event_type: 'SleepPad_LeftBed',
    category: 'behavioral',
    alarm_level: '4',
    alarm_status: 'active',
    triggered_at: dayjs().subtract(30, 'minutes').unix(),
    card_id: 'card-003',
    device_id: 'device-003',
    device_name: 'SleepPad01',
    resident_id: 'resident-003',
    resident_name: 'Bob Johnson',
    location_tag: 'Building B',
    building: 'B',
    unit_name: 'F305',
    address_display: 'Building B-B-F305',
  },
  {
    event_id: 'event-004',
    event_type: 'OfflineAlarm',
    category: 'device',
    alarm_level: '3',
    alarm_status: 'active',
    triggered_at: dayjs().subtract(15, 'minutes').unix(),
    card_id: 'card-004',
    device_id: 'device-004',
    device_name: 'Radar03',
    resident_id: 'resident-004',
    resident_name: 'Alice Brown',
    location_tag: 'Building C',
    building: 'C',
    unit_name: 'G401',
    address_display: 'Building C-C-G401',
  },
  {
    event_id: 'event-005',
    event_type: 'Radar_ApneaHypopnea',
    category: 'clinical',
    alarm_level: '0',
    alarm_status: 'resolved',
    triggered_at: dayjs().subtract(1, 'day').unix(),
    card_id: 'card-005',
    device_id: 'device-005',
    device_name: 'Radar04',
    resident_id: 'resident-005',
    resident_name: 'Charlie Wilson',
    location_tag: 'Building A',
    building: 'A',
    unit_name: 'E205',
    address_display: 'Building A-A-E205',
    handling_state: 'verified',
    handling_details: 'Patient was checked, no issues found',
    handler_id: 'user-001',
    handler_name: 'Nurse Alice',
    handled_at: dayjs().subtract(1, 'day').add(30, 'minutes').unix(),
  },
  {
    event_id: 'event-006',
    event_type: 'LowBattery',
    category: 'device',
    alarm_level: '4',
    alarm_status: 'resolved',
    triggered_at: dayjs().subtract(2, 'days').unix(),
    card_id: 'card-006',
    device_id: 'device-006',
    device_name: 'SleepPad02',
    resident_id: 'resident-006',
    resident_name: 'Diana Lee',
    location_tag: 'Building B',
    building: 'B',
    unit_name: 'F306',
    address_display: 'Building B-B-F306',
    handling_state: 'false_alarm',
    handling_details: 'Device battery replaced',
    handler_id: 'user-002',
    handler_name: 'IT Support',
    handled_at: dayjs().subtract(2, 'days').add(1, 'hour').unix(),
  },
  {
    event_id: 'event-007',
    event_type: 'Radar_AbnormalRespiratoryRate',
    category: 'clinical',
    alarm_level: '2',
    alarm_status: 'resolved',
    triggered_at: dayjs().subtract(3, 'days').unix(),
    card_id: 'card-007',
    device_id: 'device-007',
    device_name: 'Radar05',
    resident_id: 'resident-007',
    resident_name: 'Edward Davis',
    location_tag: 'Building C',
    building: 'C',
    unit_name: 'G402',
    address_display: 'Building C-C-G402',
    handling_state: 'test',
    handling_details: 'System test alarm',
    handler_id: 'user-003',
    handler_name: 'Manager Bob',
    handled_at: dayjs().subtract(3, 'days').add(15, 'minutes').unix(),
  },
]

/**
 * Generate mock alarm events result
 */
export function generateAlarmEventsResult(
  events: AlarmEvent[],
  page: number = 1,
  pageSize: number = 10,
): GetAlarmEventsResult {
  const start = (page - 1) * pageSize
  const end = start + pageSize
  const paginatedEvents = events.slice(start, end)

  return {
    items: paginatedEvents,
    pagination: {
      size: pageSize,
      page: page,
      count: paginatedEvents.length,
      total: events.length,
    },
  }
}

